             Section A:Conceptual Understanding


A1. Why are NumPy arrays preferred over Python lists?


NumPy arrays are preferred over Python lists because they are faster and more memory-efficient for numerical computations. They also support vectorized operations, which allow mathematical calculations on entire arrays without explicit Python loops. Therefore, NumPy is more suitable for handling large numerical datasets in AI/ML.


A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets? 


Vectorization means performing an operation on an entire NumPy array at once instead of using an explicit Python loop. It is faster because NumPy uses optimized operations to process many elements efficiently. For large datasets, vectorization reduces execution time and makes numerical computations more efficient.

A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each


A * B performs element-wise multiplication, where corresponding elements of A and B are multiplied. A @ B performs matrix multiplication, following matrix multiplication rules. In a neural network, A * B can be used for element-wise operations such as applying a mask, while A @ B is commonly used to calculate the weighted sum of inputs in a layer.

A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise

Broadcasting allows NumPy to perform element-wise operations on arrays with different but compatible shapes. Two dimensions are compatible when they are equal or when one of them is 1. NumPy automatically expands the smaller dimension conceptually to perform the operation.

A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why? 

Both flatten() and ravel() convert an array into a one-dimensional array. flatten() always creates a copy, while ravel() generally returns a view when possible. For memory-constrained processing of large images, I would prefer ravel() because it can avoid creating an unnecessary copy and use less memory.

A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example.

For a 2D array, axis=0 performs the aggregation down the rows, giving a result for each column. axis=1 performs the aggregation across the columns, giving a result for each row.



In [1]:
#Example:

import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[5 7 9]
[ 6 15]


A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization.

Normalization or standardization is important because numerical features may have very different scales. For example, age may range from 18 to 60, while salary may range from 20,000 to 100,000. Scaling the features puts them on comparable scales and can help many ML algorithms work more effectively.

Normalization scales values to a fixed range, usually 0 to 1, using (x - min) / (max - min). Standardization transforms values so that they have a mean of approximately 0 and a standard deviation of 1, using (x - mean) / standard deviation.

A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN? 

np.nanmean() calculates the mean while ignoring NaN values. It is useful when a dataset contains missing numerical values.

If np.mean() is directly applied to an array containing NaN, the result will generally be NaN.

A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128

For normal ML data, X.shape = (samples, features). For RGB images, the feature information is represented using height, width, and 3 color channels.

Therefore, a batch of 64 RGB images of size 128 × 128 has the shape:

(64, 128, 128, 3)

Here, 64 is the number of images, 128 × 128 is the image size, and 3 represents RGB channels.

A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed)

Reproducibility is important because it allows the same experiment to produce the same random results when repeated. This helps with debugging, comparing models, and verifying experiments.

For example:

rng = np.random.default_rng(42)

Using the same seed, such as 42, makes the generated random sequence reproducible.

               Section B – Predict the Output


In [2]:
#B1. Predict the exact output and/or resulting shape. Justify in one sentence
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)


(3, 3)


Explanation: Here, a is a 1D array and b is a 2D array with one column. When I add them, NumPy automatically adjusts the arrays using broadcasting, so the result becomes a 3×3 array. Therefore, the shape of the result is (3,3).

In [3]:
#B2. Predict the output and/or shape. [2 marks]
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])


[2 5]


Explanation: First, the numbers from 1 to 6 are arranged into 2 rows and 3 columns. In x[:,1], : means all rows and 1 represents the second column, so I get the values 2 and 5.

In [4]:
#B3. Predict the output and/or shape. [2 marks]
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])


[10 20]


Explanation: Here, I am checking which numbers are completely divisible by 10 using % 10 == 0. Only 10 and 20 satisfy this condition, so NumPy selects and prints those two values.

In [5]:
#B4. Predict the output and/or shape. [2 marks]
m = np.array([[1, 2], [3, 4]])
print(m.T @ m)


[[10 14]
 [14 20]]


Explanation: Here, .T changes the rows into columns, which is called transposing the matrix. Then @ performs matrix multiplication between the transpose and the original matrix, giving the final 2×2 matrix.

In [6]:
#B5. Predict the output and/or shape. [2 marks]
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))


nan 2.3333333333333335


Explanation: The array contains a NaN value, which represents missing data. I understood that np.mean() gives nan because it considers the missing value, while np.nanmean() ignores NaN and calculates the average of the remaining values.

In [7]:
#B6. Predict the output and/or shape. [2 marks]
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)


[0 1 1]


Explanation: Here, np.where() checks each value against the condition x > 15. Since 10 is not greater than 15 it becomes 0, while 20 and 30 satisfy the condition and become 1.

In [8]:
#B7. Predict the output and/or shape. [2 marks]
a = np.zeros((3, 4))
print(a.ndim, a.size)


2 12


Explanation: The zeros((3,4)) creates an array with 3 rows and 4 columns. I understood that ndim tells me the number of dimensions, which is 2, and size tells me the total number of elements, which is 3 × 4 = 12.

In [9]:
#B8. Predict the output and/or shape. [2 marks]
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])


[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Explanation: First, the numbers 1 to 12 are arranged into 3 rows and 4 columns. The [::-1] used for both rows and columns reverses their order, so the first element becomes 12 and the last element becomes 1.

              Section C – Coding / Implementation


In [10]:
#C1. Pass/Fail using np.where()
import numpy as np

scores = np.array([35, 45, 67, 28, 90])

labels = np.where(scores >= 40, 'P', 'F')

print(labels)

['F' 'P' 'P' 'F' 'P']


Explanation: Here, I used np.where() to check whether each student's score is 40 or above. If the condition is true, it gives P, otherwise it gives F. So, 35 and 28 are Fail, while 45, 67 and 90 are Pass.

In [11]:
#C2. Standardization function
import numpy as np

def standardize(x):
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std

x = np.array([10, 20, 30, 40, 50])

result = standardize(x)

print(result)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Explanation: Here, I calculated the mean and standard deviation of the values and used them to standardize the data. After standardization, the values are represented based on how far they are from the mean. The middle value becomes 0, while values below and above the mean get negative and positive values.

In [12]:
#C3. Combine two batches
import numpy as np

batch1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

batch2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

combined = np.vstack((batch1, batch2))

print(combined)
print(combined.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


Explanation: Here, both batches have 3 columns, so I used vstack() to place the second batch below the first batch. The two 2×3 arrays become one 4×3 array. I understood that vstack() combines arrays vertically, meaning row by row.

In [13]:
#C4. Standardize X with shape (100, 5)
import numpy as np

X = np.random.default_rng(42).random((100, 5))

mean = X.mean(axis=0)
std = X.std(axis=0)

X_standardized = (X - mean) / std

print(X_standardized.shape)

(100, 5)


Explanation: Here, I created a dataset with 100 rows and 5 features. Using axis=0, I calculated the mean and standard deviation separately for each column and then standardized the values. The shape remains (100,5) because standardization changes the values, not the number of rows or columns.

In [14]:
#C5. Linear prediction and MSE
import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])
b = 2.0

y_true = np.array([4, 6, 8])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predictions:", y_pred)
print("MSE:", mse)

Predictions: [4.5 6.  7.5]
MSE: 0.16666666666666666


Explanation: Here, I used matrix multiplication between X and w and then added the bias b to get the predicted values. I then compared these predictions with the actual values using Mean Squared Error (MSE). The MSE is small because the predicted values are close to the actual values.

In [15]:
#C6. Reproducible random data
import numpy as np

rng1 = np.random.default_rng(42)
data1 = rng1.normal(size=(10, 3))

rng2 = np.random.default_rng(42)
data2 = rng2.normal(size=(10, 3))

print(data1.shape)
print(np.array_equal(data1, data2))

(10, 3)
True


Explanation: Here, I used the same seed value 42 for both random number generators. Even though the values are randomly generated, using the same seed produces the same data. Therefore, array_equal() returns True, showing that both arrays are exactly the same.

In [16]:
#C7. Image min-max normalization
import numpy as np

image = np.array([[0, 128, 255],
                  [64, 192, 255]])

normalized = (image - image.min()) / (image.max() - image.min())

print(normalized)

[[0.         0.50196078 1.        ]
 [0.25098039 0.75294118 1.        ]]


Explanation: Here, I converted the image values into a range between 0 and 1 using min-max normalization. The minimum value becomes 0 and the maximum value becomes 1. The other pixel values are converted proportionally between these two values.

In [17]:
#C8. Average pixel value of each image
import numpy as np

images = np.random.default_rng(42).random((4, 28, 28, 3))

average_values = images.mean(axis=(1, 2, 3))

print(average_values)
print(average_values.shape)

[0.49879444 0.49546077 0.48993754 0.50644914]
(4,)


Explanation: Here, I created 4 RGB images, where each image has dimensions 28 × 28 × 3. By using axis=(1,2,3), I calculated the average pixel value of each complete image. Therefore, the result contains 4 average values, one for each image.

            Section D — Applied / Scenario-Based problems
            

D1. Data Preprocessing Pipeline

You are given a raw 1D or 2D NumPy array containing NaN values.
Describe, step by step, the NumPy operations you would apply to:
(a) detect missing values,
(b) handle them appropriately and justify your strategy, and
(c) normalize or standardize the clean data before it is fed to a model.

Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.


Steps

Use np.isnan() to detect missing values.
Calculate a suitable replacement value, such as the mean of the non-missing values.
Replace the missing values using np.where().
Standardize the cleaned data using its mean and standard deviation.

In [19]:
import numpy as np
data = np.array([10.0, 20.0, np.nan, 40.0, 50.0])

# Step 1: Detect missing values
missing = np.isnan(data)
print("Missing values:", missing)

# Step 2: Calculate mean excluding NaN 
mean_value = np.nanmean(data)

# Step 3: Replace NaN with the mean 
clean_data = np.where(missing, mean_value, data)

# Step 4: Standardize the clean data
mean = np.mean(clean_data)
std = np.std(clean_data)
standardized_data = (clean_data - mean) / std

print("Clean data:", clean_data)
print("Standardized data:", standardized_data)

Missing values: [False False  True False False]
Clean data: [10. 20. 30. 40. 50.]
Standardized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Explanation: Here, I created a batch of 16 RGB images, where each image has a size of 64 × 64. Using mean(axis=0), I calculated the average value of all 16 images pixel by pixel. Therefore, the batch dimension is removed and the average image has the shape (64,64,3).


                 D2 — Image Batch Understanding

1.Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.

A single RGB image of size 64 × 64 has the shape:

(64, 64, 3)

Here:

64 → image height
64 → image width
3 → RGB color channels (Red, Green, Blue)

A batch of 16 RGB images has the shape:

(16, 64, 64, 3)

Here, the first 16 represents the number of images in the batch.

Statement:
I understood that a single RGB image needs three dimensions: height, width, and color channels. When multiple images are stored together, one extra dimension is added at the beginning to represent the number of images in the batch.





2. Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.
import numpy as np

rng = np.random.default_rng(42)

images = rng.integers(
    0, 256,
    size=(16, 64, 64, 3)
)

print(images.shape)

Output:

(16, 64, 64, 3)

Statemnet:
Here, I used rng.integers(0, 256) to generate random pixel values from 0 to 255. I created 16 images, and each image has 64 × 64 pixels with 3 RGB channels, so the final shape is (16, 64, 64, 3).

3. Compute the average image of the batch, meaning the element-wise mean across all 16 images.
average_image = images.mean(axis=0)

print(average_image.shape)

Output:

(64, 64, 3)

Statement:
Here, axis=0 represents the 16 images in the batch. By taking the mean along this axis, NumPy calculates the average value of each corresponding pixel across all 16 images. The result is one average RGB image.

4. State the shape of your result and explain why.

The shape of the average image is:

(64, 64, 3)

The original batch has:

(16, 64, 64, 3)

When I use:

images.mean(axis=0)

the first dimension (16) is reduced because the 16 images are averaged together. The remaining dimensions are the height, width, and RGB channels.

Statement:
I understood that averaging the 16 images combines the corresponding pixels from all images into one image. Therefore, the batch dimension 16 disappears, while the image dimensions 64 × 64 × 3 remain unchanged.

In [20]:
import numpy as np
rng = np.random.default_rng(42)

# Create 16 RGB images with pixel values from 0 to 255
images = rng.integers(0, 256, size=(16, 64, 64, 3))
print("Batch shape:", images.shape)

# Average across the image/batch dimension
average_image = images.mean(axis=0)
print("Average image shape:", average_image.shape)

Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


Explanation: axis=0 averages corresponding pixels across all 16 images while preserving the height, width, and RGB channels.

                 D3 — Debug the Model Code

Bug 1 — Weight vector has the wrong shape

X has shape:

(3, 2)

Therefore, the weight vector must contain 2 weights, one for each feature.

However:

w = np.array([0.5, 1.0, 0.2])

has shape:

(3,)

Matrix multiplication:

(3, 2) @ (3,)

is not compatible.

Therefore, w should have shape (2,).

Bug 2 — Incorrect MSE formula

The original expression is:

np.mean(y_true - y_pred ** 2)

Because exponentiation has higher precedence, Python interprets this as:

np.mean(y_true - (y_pred ** 2))

But MSE requires the difference to be squared:

np.mean((y_true - y_pred) ** 2)

In [23]:
import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

# Two features -> two weights
w = np.array([0.5, 1.0])

b = 2.0

# Prediction
y_pred = X @ w + b

y_true = np.array([10, 20, 30])

# Correct MSE formula
mse = np.mean((y_true - y_pred) ** 2)

print("Predictions:", y_pred)
print("MSE:", mse)



Predictions: [4.5 6.  7.5]
MSE: 244.16666666666666


Explanation:Here, I understood that the number of weights must match the number of columns in X. Since X has 2 columns, w should contain 2 values. I also corrected the MSE formula by putting the complete difference inside brackets before squaring, so the error is calculated correctly.

              Section E — Bonus / Challenge

In [24]:
#E1. Per-Column Min-Max Normalization
import numpy as np

X = np.array([[10, 100, 1000],
              [20, 200, 2000],
              [30, 300, 3000]])

column_min = X.min(axis=0)
column_max = X.max(axis=0)

normalized = (X - column_min) / (column_max - column_min)

print(normalized)

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


Explanation: Here, I performed min-max normalization separately for each column by using axis=0. The smallest value in each column becomes 0 and the largest becomes 1. This makes the different features comparable by putting them into the same range.

In [25]:
#E2. Three-Level Score Classification
import numpy as np

scores = np.array([25, 40, 55, 70, 85])

result = np.where(
    scores < 40,
    "Fail",
    np.where(scores <= 70, "Average", "Excellent")
)

print(result)

['Fail' 'Average' 'Average' 'Average' 'Excellent']


Explanation: Here, I used nested np.where() to divide the scores into three categories. Scores below 40 are marked as Fail, scores from 40 to 70 are Average, and scores above 70 are Excellent. This helped me understand how multiple conditions can be handled using NumPy.